name: testing e2e 

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - "*.md"
      - "assets/**"
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dagger Version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@v0.0.1

      - name: Test E2E satellite (GitHub Action)
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: test-end-to-end

      - name: Test E2E satellite (Direct CLI)
        run: dagger call test-end-to-end
