name: testing e2e 

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - "*.md"
      - "assets/**"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dagger Version
        uses: sagikazarmark/dagger-version-action@v0.0.1

      - name: Test E2E satellite
        uses: dagger/dagger-for-github@8.0.0
        with:
           version: ${{ steps.dagger_version.outputs.version }}
          verb: call
          args: test-end-to-end
